server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: H3idyYP
  jpa:
    show.sql: true
    hibernate:
      ddl-auto: update